// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.12
// source: github_msg.proto

package msg

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GithubKPMsg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Repo         string        `protobuf:"bytes,1,opt,name=repo,proto3" json:"repo,omitempty"`
	Star         int64         `protobuf:"varint,2,opt,name=star,proto3" json:"star,omitempty"`
	Fork         int64         `protobuf:"varint,3,opt,name=fork,proto3" json:"fork,omitempty"`
	Watch        int64         `protobuf:"varint,4,opt,name=watch,proto3" json:"watch,omitempty"`
	Dependencies []*Dependency `protobuf:"bytes,5,rep,name=dependencies,proto3" json:"dependencies,omitempty"`
	Timestamp    int64         `protobuf:"varint,6,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Description  string        `protobuf:"bytes,7,opt,name=description,proto3" json:"description,omitempty"`
	License      string        `protobuf:"bytes,8,opt,name=license,proto3" json:"license,omitempty"`
	Author       string        `protobuf:"bytes,9,opt,name=author,proto3" json:"author,omitempty"`
	Keywords     []string      `protobuf:"bytes,10,rep,name=keywords,proto3" json:"keywords,omitempty"`
	Homepage     string        `protobuf:"bytes,11,opt,name=homepage,proto3" json:"homepage,omitempty"`
}

func (x *GithubKPMsg) Reset() {
	*x = GithubKPMsg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_github_msg_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GithubKPMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GithubKPMsg) ProtoMessage() {}

func (x *GithubKPMsg) ProtoReflect() protoreflect.Message {
	mi := &file_github_msg_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GithubKPMsg.ProtoReflect.Descriptor instead.
func (*GithubKPMsg) Descriptor() ([]byte, []int) {
	return file_github_msg_proto_rawDescGZIP(), []int{0}
}

func (x *GithubKPMsg) GetRepo() string {
	if x != nil {
		return x.Repo
	}
	return ""
}

func (x *GithubKPMsg) GetStar() int64 {
	if x != nil {
		return x.Star
	}
	return 0
}

func (x *GithubKPMsg) GetFork() int64 {
	if x != nil {
		return x.Fork
	}
	return 0
}

func (x *GithubKPMsg) GetWatch() int64 {
	if x != nil {
		return x.Watch
	}
	return 0
}

func (x *GithubKPMsg) GetDependencies() []*Dependency {
	if x != nil {
		return x.Dependencies
	}
	return nil
}

func (x *GithubKPMsg) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *GithubKPMsg) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *GithubKPMsg) GetLicense() string {
	if x != nil {
		return x.License
	}
	return ""
}

func (x *GithubKPMsg) GetAuthor() string {
	if x != nil {
		return x.Author
	}
	return ""
}

func (x *GithubKPMsg) GetKeywords() []string {
	if x != nil {
		return x.Keywords
	}
	return nil
}

func (x *GithubKPMsg) GetHomepage() string {
	if x != nil {
		return x.Homepage
	}
	return ""
}

type Dependency struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Package string `protobuf:"bytes,1,opt,name=package,proto3" json:"package,omitempty"`
	Version string `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
}

func (x *Dependency) Reset() {
	*x = Dependency{}
	if protoimpl.UnsafeEnabled {
		mi := &file_github_msg_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Dependency) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Dependency) ProtoMessage() {}

func (x *Dependency) ProtoReflect() protoreflect.Message {
	mi := &file_github_msg_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Dependency.ProtoReflect.Descriptor instead.
func (*Dependency) Descriptor() ([]byte, []int) {
	return file_github_msg_proto_rawDescGZIP(), []int{1}
}

func (x *Dependency) GetPackage() string {
	if x != nil {
		return x.Package
	}
	return ""
}

func (x *Dependency) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

var File_github_msg_proto protoreflect.FileDescriptor

var file_github_msg_proto_rawDesc = []byte{
	0x0a, 0x10, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x5f, 0x6d, 0x73, 0x67, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x06, 0x6b, 0x70, 0x2e, 0x6d, 0x73, 0x67, 0x22, 0xc1, 0x02, 0x0a, 0x0b, 0x47,
	0x69, 0x74, 0x68, 0x75, 0x62, 0x4b, 0x50, 0x4d, 0x73, 0x67, 0x12, 0x12, 0x0a, 0x04, 0x72, 0x65,
	0x70, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x72, 0x65, 0x70, 0x6f, 0x12, 0x12,
	0x0a, 0x04, 0x73, 0x74, 0x61, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x73, 0x74,
	0x61, 0x72, 0x12, 0x12, 0x0a, 0x04, 0x66, 0x6f, 0x72, 0x6b, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x04, 0x66, 0x6f, 0x72, 0x6b, 0x12, 0x14, 0x0a, 0x05, 0x77, 0x61, 0x74, 0x63, 0x68, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x77, 0x61, 0x74, 0x63, 0x68, 0x12, 0x36, 0x0a, 0x0c,
	0x64, 0x65, 0x70, 0x65, 0x6e, 0x64, 0x65, 0x6e, 0x63, 0x69, 0x65, 0x73, 0x18, 0x05, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x12, 0x2e, 0x6b, 0x70, 0x2e, 0x6d, 0x73, 0x67, 0x2e, 0x44, 0x65, 0x70, 0x65,
	0x6e, 0x64, 0x65, 0x6e, 0x63, 0x79, 0x52, 0x0c, 0x64, 0x65, 0x70, 0x65, 0x6e, 0x64, 0x65, 0x6e,
	0x63, 0x69, 0x65, 0x73, 0x12, 0x1c, 0x0a, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d,
	0x70, 0x18, 0x06, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61,
	0x6d, 0x70, 0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f,
	0x6e, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70,
	0x74, 0x69, 0x6f, 0x6e, 0x12, 0x18, 0x0a, 0x07, 0x6c, 0x69, 0x63, 0x65, 0x6e, 0x73, 0x65, 0x18,
	0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6c, 0x69, 0x63, 0x65, 0x6e, 0x73, 0x65, 0x12, 0x16,
	0x0a, 0x06, 0x61, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x18, 0x09, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06,
	0x61, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x12, 0x1a, 0x0a, 0x08, 0x6b, 0x65, 0x79, 0x77, 0x6f, 0x72,
	0x64, 0x73, 0x18, 0x0a, 0x20, 0x03, 0x28, 0x09, 0x52, 0x08, 0x6b, 0x65, 0x79, 0x77, 0x6f, 0x72,
	0x64, 0x73, 0x12, 0x1a, 0x0a, 0x08, 0x68, 0x6f, 0x6d, 0x65, 0x70, 0x61, 0x67, 0x65, 0x18, 0x0b,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x68, 0x6f, 0x6d, 0x65, 0x70, 0x61, 0x67, 0x65, 0x22, 0x40,
	0x0a, 0x0a, 0x44, 0x65, 0x70, 0x65, 0x6e, 0x64, 0x65, 0x6e, 0x63, 0x79, 0x12, 0x18, 0x0a, 0x07,
	0x70, 0x61, 0x63, 0x6b, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x70,
	0x61, 0x63, 0x6b, 0x61, 0x67, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f,
	0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e,
	0x42, 0x07, 0x5a, 0x05, 0x2e, 0x2f, 0x6d, 0x73, 0x67, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_github_msg_proto_rawDescOnce sync.Once
	file_github_msg_proto_rawDescData = file_github_msg_proto_rawDesc
)

func file_github_msg_proto_rawDescGZIP() []byte {
	file_github_msg_proto_rawDescOnce.Do(func() {
		file_github_msg_proto_rawDescData = protoimpl.X.CompressGZIP(file_github_msg_proto_rawDescData)
	})
	return file_github_msg_proto_rawDescData
}

var file_github_msg_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_github_msg_proto_goTypes = []interface{}{
	(*GithubKPMsg)(nil), // 0: kp.msg.GithubKPMsg
	(*Dependency)(nil),  // 1: kp.msg.Dependency
}
var file_github_msg_proto_depIdxs = []int32{
	1, // 0: kp.msg.GithubKPMsg.dependencies:type_name -> kp.msg.Dependency
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_github_msg_proto_init() }
func file_github_msg_proto_init() {
	if File_github_msg_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_github_msg_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GithubKPMsg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_github_msg_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Dependency); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_github_msg_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_github_msg_proto_goTypes,
		DependencyIndexes: file_github_msg_proto_depIdxs,
		MessageInfos:      file_github_msg_proto_msgTypes,
	}.Build()
	File_github_msg_proto = out.File
	file_github_msg_proto_rawDesc = nil
	file_github_msg_proto_goTypes = nil
	file_github_msg_proto_depIdxs = nil
}
